### ISSUE TITLE
Cannot enlarge memory arrays

### ISSUE THREAD

**Issue by mertakdut** [mmig/libflac.js#5]
Hello,

Getting the error when I decode a mp3 file to audiobuffer (using web audio api) and then trying to encode it to flac with almost the same stuff on readme file. Works fine for files less than 1mb.

```
ERROR Error: Uncaught (in promise): abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ") at Error
    at jsStackTrace (http://localhost:4200/scripts.bundle.js:1179:13)
    at stackTrace (http://localhost:4200/scripts.bundle.js:1196:22)
    at abort (http://localhost:4200/scripts.bundle.js:45000:44)
    at abortOnCannotGrowMemory (http://localhost:4200/scripts.bundle.js:1220:3)
    at enlargeMemory (http://localhost:4200/scripts.bundle.js:1224:3)
    at Function.dynamicAlloc [as alloc] (http://localhost:4200/scripts.bundle.js:350:177)
    at _sbrk (http://localhost:4200/scripts.bundle.js:5582:28)
    at Object._malloc (http://localhost:4200/scripts.bundle.js:40583:15)
    at Object.FLAC__stream_encoder_process_interleaved (http://localhost:4200/scripts.bundle.js:45852:20)
    at encodeFlac (webpack-internal:///./src/assets/flac-encoder.js:60:26)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
    at jsStackTrace (http://localhost:4200/scripts.bundle.js:1179:13)
    at stackTrace (http://localhost:4200/scripts.bundle.js:1196:22)
    at abort (http://localhost:4200/scripts.bundle.js:45000:44)
    at abortOnCannotGrowMemory (http://localhost:4200/scripts.bundle.js:1220:3)
    at enlargeMemory (http://localhost:4200/scripts.bundle.js:1224:3)
    at Function.dynamicAlloc [as alloc] (http://localhost:4200/scripts.bundle.js:350:177)
    at _sbrk (http://localhost:4200/scripts.bundle.js:5582:28)
    at Object._malloc (http://localhost:4200/scripts.bundle.js:40583:15)
    at Object.FLAC__stream_encoder_process_interleaved (http://localhost:4200/scripts.bundle.js:45852:20)
    at encodeFlac (webpack-internal:///./src/assets/flac-encoder.js:60:26)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
    at resolvePromise (webpack-internal:///./node_modules/zone.js/dist/zone.js:809:31)
    at eval (webpack-internal:///./node_modules/zone.js/dist/zone.js:861:17)
    at ZoneDelegate.invokeTask (webpack-internal:///./node_modules/zone.js/dist/zone.js:421:31)
    at Object.onInvokeTask (webpack-internal:///./node_modules/@angular/core/esm5/core.js:4956:33)
    at ZoneDelegate.invokeTask (webpack-internal:///./node_modules/zone.js/dist/zone.js:420:36)
    at Zone.runTask (webpack-internal:///./node_modules/zone.js/dist/zone.js:188:47)
    at drainMicroTaskQueue (webpack-internal:///./node_modules/zone.js/dist/zone.js:595:35)
    at <anonymous>
```

Getting the same error from the [sample site](https://mmig.github.io/libflac.js/example/encode.html) as well.

**Comment by russaa** [comment]
I'll look into it, but it will probably take me a few days until I come around to it

**Comment by russaa** [comment]
OK, the JS files in `/dist` have been recompiled with `ALLOW_MEMORY_GROWTH=1` setting -- this should fix your issue

**Comment by russaa** [comment]
as a side note:  

it would probably be a good idea for large audio data, to not feed the data all at once to the encoder, but instead call `Flac.FLAC__stream_encoder_process_interleaved()` multiple times with smaller chunks of the audio data
